### ISSUE TITLE
Missing glCopyTexSubImage2D and glCopyTexImage2D

### ISSUE THREAD

**Issue by Fancy2209** [devkitPro/opengx#79]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>
[ Note: If you include links to websites who promote and encourage intellectual property infringment then those links and references to them will be removed. People who persistently include such links and/or argue about their removal will be blocked; ]</br>

### What's the issue you encountered?
I am working on a port of Sonic Robo Blast 2 2.1.25, I attemtped to build it with OpenGL on, but noticed that the linker fails
From the output it seems that these 2 missing functions are the culprits:
- glCopyTexSubImage2D
- glCopyTexImage2D
I feel it'd make sense to either, implement them, stub them, or temporarily comment them out of the GL headers so it's easier to catch they're missing.
Linker Output:
```
Linking srb2wii.elf...
/opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld: ../objs/Wii/SDL/Release/r_opengl.o: in function `StartScreenWipe':
/home/paulo/SRB2Wii/src/hardware/r_opengl/r_opengl.c:2235:(.text.StartScreenWipe+0x6c): undefined reference to `glCopyTexSubImage2D'
/opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld: /home/paulo/SRB2Wii/src/hardware/r_opengl/r_opengl.c:2230:(.text.StartScreenWipe+0x130): undefined reference to `glCopyTexImage2D'
/opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld: ../objs/Wii/SDL/Release/r_opengl.o: in function `EndScreenWipe':
/home/paulo/SRB2Wii/src/hardware/r_opengl/r_opengl.c:2275:(.text.EndScreenWipe+0x6c): undefined reference to `glCopyTexSubImage2D'
/opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld: /home/paulo/SRB2Wii/src/hardware/r_opengl/r_opengl.c:2270:(.text.EndScreenWipe+0x130): undefined reference to `glCopyTexImage2D'
/opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld: ../objs/Wii/SDL/Release/r_opengl.o: in function `MakeScreenTexture':
/home/paulo/SRB2Wii/src/hardware/r_opengl/r_opengl.c:2479:(.text.MakeScreenTexture+0x6c): undefined reference to `glCopyTexSubImage2D'
/opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld: /home/paulo/SRB2Wii/src/hardware/r_opengl/r_opengl.c:2474:(.text.MakeScreenTexture+0x130): undefined reference to `glCopyTexImage2D'
/opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld: ../objs/Wii/SDL/Release/r_opengl.o: in function `MakeScreenFinalTexture':
/home/paulo/SRB2Wii/src/hardware/r_opengl/r_opengl.c:2518:(.text.MakeScreenFinalTexture+0x6c): undefined reference to `glCopyTexSubImage2D'
/opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld: /home/paulo/SRB2Wii/src/hardware/r_opengl/r_opengl.c:2513:(.text.MakeScreenFinalTexture+0x130): undefined reference to `glCopyTexImage2D'
collect2: error: ld returned 1 exit status
make: *** [Makefile:635: ../bin/Wii/Release/srb2wii.elf] Error 1
```

### How can the issue be reproduced?

Try to link an app using glCopyTexSubImage2D, or glCopyTexImage2D
For example https://github.com/Fancy2209/SRB2Wii
(to build cd to the src dir and run make WII=1)

### Environment?
endeavourOS, I do use a unnoficial wii-curl package but it is not related to the issue here
### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by WinterMute** [comment]
As amazing though @mardy's work here is, opengx is still very much a work in progress and there are still features missing. These functions are not yet implemented but will be in time https://github.com/devkitPro/opengx/blob/master/src/functions.c#L104-L107

**Comment by mardy** [comment]
Oh, it turns out I was not subscribed to this project's issues, so thanks @WinterMute for mentioning me :-)

@Fancy2209, indeed, the functions are not implemented yet, but I believe that it shouldn't be too hard to come up with a quick implementation using glReadPixels+glTex(Sub)Image2D. You could give it a try, if you don't want to wait for me :-)

**Comment by Fancy2209** [comment]
> Oh, it turns out I was not subscribed to this project's issues, so thanks @WinterMute for mentioning me :-)
> 
> @Fancy2209, indeed, the functions are not implemented yet, but I believe that it shouldn't be too hard to come up with a quick implementation using glReadPixels+glTex(Sub)Image2D. You could give it a try, if you don't want to wait for me :-)

And it seems github never notified me of your reply!
yeah that seems simple enough, will try and post results
